import { NCR, Equipment } from "./types"

// ─── Sample NCRs — Indian Shipyard Context ───────────────────────────────────
// Vessels from Cochin Shipyard, L&T Shipbuilding, Mazagon Dock, GRSE scenarios
// People names, IRS class references, INR costs

export const SAMPLE_NCRS: NCR[] = [
  {
    id: "NCR-2024-0001",
    vessel: "INS Vikrant (Yard No. 3001)", yard: "Cochin Shipyard Ltd (CSL)",
    imoNumber: "9816730",
    location: "Block P-14 / Frame 112–118 / Upper Deck",
    drawingRef: "CSL-STR-3001-UKD-014 Rev.2",
    defectType: "Weld Defect", severity: "Major",
    raisedDate: "2024-10-08", targetDate: "2024-10-15",
    status: "Closed", closedDate: "2024-10-13",
    description: "Undercut defect on bracket-to-longitudinal fillet weld at Fr.115. Measured depth 1.4mm, exceeding IRS permissible limit of 0.5mm. Total affected weld length approx. 320mm.",
    rootCause: "Workmanship",
    department: "Hull Structure",
    raisedBy: "Smt. Deepa Nair — QA Inspector, CSL",
    responsible: "Shri. Ramesh Pillai — DGM, Hull Production",
    authorizedBy: "Shri. Arun Menon — AGM, Quality Assurance",
    assignedTo: "Shri. Murugan S. — Senior Welding Foreman",
    followedBy: "Shri. Jithin Kumar — QA Engineer",
    reviewedBy: "Surveyor Krishnamurthy — IRS, Kochi Office",
    classSociety: "IRS", classRef: "IRS/CSL/2024/NCR/0118",
    correctiveAction: "Defective weld ground out to base metal. Re-welded with pre-heat 75°C as per WPS-CSL-007. Post-weld VT and UT inspection passed. IRS surveyor re-inspection completed.",
    lessonLearned: "Bracket-to-longitudinal welds at frames 110–120 in P-14 block require mandatory pre-heat due to plate thickness >20mm. Added to block pre-assembly checklist and WPS-CSL-007.",
    currency: "INR", cost: 28500,
  },
  {
    id: "NCR-2024-0002",
    vessel: "MT Kalpana (Yard No. 445)", yard: "L&T Shipbuilding, Kattupalli",
    location: "Engine Room / HFO Pipe Run E-07 / Fr.60",
    drawingRef: "LT-PIPE-445-ER-E07 Rev.1",
    defectType: "Piping", severity: "Critical",
    raisedDate: "2024-11-05", targetDate: "2024-11-10",
    status: "Overdue",
    description: "HFO suction pipe flange face damage during block erection. Surface finish Ra 6.3μm achieved vs required Ra 3.2μm per IRS rules. Risk of fuel leakage during sea trial.",
    rootCause: "Workmanship",
    department: "Outfitting",
    raisedBy: "Shri. Venkatesh Iyer — Outfitting Inspector",
    responsible: "Shri. Subramaniam R. — Manager, Pipe Outfitting",
    authorizedBy: "Shri. T. Annamalai — AGM, QA & Inspection",
    assignedTo: "Shri. Selvam K. — Pipe Fitting Supervisor",
    followedBy: "Smt. Priya Chandran — QA Engineer, Piping",
    reviewedBy: "Surveyor D. Raghunathan — BV, Chennai",
    classSociety: "BV", classRef: "BV/LT/445/2024/NCR-CR-009",
    correctiveAction: "Replacement flange on order from Chennai. Estimated delivery 5 days delayed. Temporary protection applied.",
    currency: "INR", cost: 145000,
  },
  {
    id: "NCR-2024-0003",
    vessel: "OSV Sagar Nidhi II (Yard No. 512)", yard: "Hindustan Shipyard Ltd (HSL), Visakhapatnam",
    location: "Main Deck / Zone D-3 / Starboard",
    drawingRef: "HSL-PAINT-512-MD-003",
    defectType: "Painting", severity: "Minor",
    raisedDate: "2024-11-18", targetDate: "2024-11-28",
    status: "In Progress",
    description: "Holiday defects on epoxy primer coat, main deck starboard side. DFT measured 62–68 microns vs specified 75±10 microns in 3 patches approx. 2.5m² total. Climate conditions not recorded during application.",
    rootCause: "Environmental",
    department: "Painting",
    raisedBy: "Shri. Balasubramanian — Paint Inspector (NACE Level II)",
    responsible: "Shri. Ravi Shankar — Manager, Painting & Blasting",
    authorizedBy: "Shri. C. V. Naidu — DGM, Production",
    assignedTo: "Shri. Arjun Rao — Paint Supervisor",
    followedBy: "Shri. Santhosh Kumar — QA Coordinator",
    classSociety: "IRS", classRef: "IRS/HSL/2024/NCR/0092",
    correctiveAction: "Spot sweep blast and recoat scheduled. Climate log (RH, temp, dew point) to be maintained throughout.",
    currency: "INR", cost: 18200,
  },
  {
    id: "NCR-2024-0004",
    vessel: "GRSE Fast Patrol Vessel P-450", yard: "Garden Reach Shipbuilders & Engineers (GRSE), Kolkata",
    location: "Wheelhouse / Deck 4 / Cable Tray CT-14",
    drawingRef: "GRSE-ELEC-P450-D4-CT14 Rev.3",
    defectType: "Electrical", severity: "Minor",
    raisedDate: "2024-11-25", targetDate: "2024-12-10",
    status: "Open",
    description: "Cable tray CT-14 misaligned by 18mm from approved drawing reference. BIS IS 13384 standard requires alignment within ±5mm. Affects cable bending radius for 3 x 16mm² power cables.",
    rootCause: "Design Issue",
    department: "Electrical",
    raisedBy: "Smt. Priya Rajan — Electrical Inspector",
    responsible: "Shri. Debashis Pal — Asst. Manager, Electrical Outfitting",
    authorizedBy: "Shri. A. K. Chatterjee — Manager, QA",
    assignedTo: "Shri. Suresh Babu — Electrical Foreman",
    followedBy: "Shri. Nitin Ghosh — QA Engineer",
    reviewedBy: "Surveyor S. Bhattacharya — IRS, Kolkata",
    classSociety: "IRS", classRef: "IRS/GRSE/2024/NCR/0047",
    correctiveAction: "Design clarification raised with Naval Architecture dept. Awaiting revised drawing approval.",
    currency: "INR", cost: 9800,
  },
  {
    id: "NCR-2024-0005",
    vessel: "MT Bharat Gaurav (Yard No. 449)", yard: "L&T Shipbuilding, Kattupalli",
    location: "Block A-02 / Keel Plate / Fr.10–15",
    drawingRef: "LT-STR-449-KL-A02 Rev.1",
    defectType: "Hull Plate", severity: "Major",
    raisedDate: "2024-09-12", targetDate: "2024-09-20",
    status: "Closed", closedDate: "2024-09-18",
    description: "Keel plate distortion — max deviation 9.2mm over 2m length measured by straight edge. IRS flatness tolerance: 5mm/2m. Caused during block assembly due to inadequate support jig spacing.",
    rootCause: "Process Gap",
    department: "Hull Structure",
    raisedBy: "Shri. Mohan Das — QA Inspector, Hull",
    responsible: "Shri. Balaji T. — Manager, Block Assembly",
    authorizedBy: "Shri. T. Annamalai — AGM, QA & Inspection",
    assignedTo: "Shri. Saravanan M. — Hull Foreman",
    followedBy: "Shri. Deepak Verma — QA Engineer",
    reviewedBy: "Surveyor D. Raghunathan — BV, Chennai",
    classSociety: "BV", classRef: "BV/LT/449/2024/NCR-MA-014",
    correctiveAction: "Flame straightening applied by certified operator. Thickness check by UT confirmed no reduction. BV surveyor re-inspection passed. Jig spacing increased to 600mm for future keel blocks.",
    lessonLearned: "Keel plate support jig must be spaced max 600mm for plates >14mm thickness. Pre-erection flatness check mandatory. Added to Procedure-LT-HULL-021.",
    currency: "INR", cost: 67000,
  },
  {
    id: "NCR-2024-0006",
    vessel: "INS Nilgiri (Yard No. P17A-Y1001)", yard: "Mazagon Dock Shipbuilders Ltd (MDL), Mumbai",
    location: "Machinery Space / DG Room / DG-02",
    drawingRef: "MDL-MACH-Y1001-DG02 Rev.4",
    defectType: "Machinery", severity: "Critical",
    raisedDate: "2024-12-03", targetDate: "2024-12-07",
    status: "Open",
    description: "Aux DG-02 (Kirloskar 750kVA) excessive vibration during 4-hour load trial at 100% load. Vibration level 21.4mm/s (velocity RMS) measured on drive end bearing; IRS limit 7.1mm/s. Suspected misalignment post-installation.",
    rootCause: "Workmanship",
    department: "Machinery",
    raisedBy: "Shri. Vijay Sawant — Commissioning Engineer, Machinery",
    responsible: "Shri. Prakash Desai — DGM, Machinery Outfitting",
    authorizedBy: "Shri. R. N. Kulkarni — GM, Production",
    assignedTo: "Shri. Durai Murugan — Machinery Supervisor",
    followedBy: "Shri. Rahul Joshi — QA Engineer, Machinery",
    reviewedBy: "Surveyor Capt. Mehta — IRS, Mumbai",
    classSociety: "IRS", classRef: "IRS/MDL/2024/NCR/CR-0031",
    correctiveAction: "Dynamic alignment check by Kirloskar service engineer in progress. Laser alignment equipment mobilised.",
    currency: "INR", cost: 285000,
  },
  {
    id: "NCR-2024-0007",
    vessel: "MV Shoft Kabir (Yard No. 078)", yard: "Shoft Shipyard Pvt. Ltd., Bharuch",
    location: "Cargo Hold No. 2 / Tank Top / Fr.42–48",
    drawingRef: "SHOFT-STR-078-TT-H02 Rev.1",
    defectType: "Weld Defect", severity: "Major",
    raisedDate: "2024-11-14", targetDate: "2024-11-22",
    status: "Closed", closedDate: "2024-11-20",
    description: "Porosity cluster found in tank top butt weld (weld seam TT-H2-09) during radiographic examination. 4 pores in a 50mm length; max pore diameter 2.1mm. IRS Rules for Steel Ships (Part 2, Ch.13) limit: max pore diameter 1.5mm, max 3 pores per 50mm. Total affected seam length 320mm.",
    rootCause: "Workmanship",
    department: "Hull Structure",
    raisedBy: "Shri. Sasi — QA Inspector, Hull",
    responsible: "Shri. Pravin — Manager, Hull Fabrication",
    authorizedBy: "Shri. Saibal — AGM, Quality Assurance",
    assignedTo: "Shri. Maan Singh — Welding Foreman",
    followedBy: "Shri. Rahul — QA Engineer",
    reviewedBy: "Surveyor V. Krishnan — IRS, Surat",
    classSociety: "IRS", classRef: "IRS/SHOFT/2024/NCR/0039",
    correctiveAction: "Defective weld zone cut out by gouging. Weld joint re-prepared and back-gouged. Re-welded by Welder 2G qualified (WPS-SHOFT-TT-003). RT re-examination: 3 films cleared. IRS surveyor acceptance obtained.",
    lessonLearned: "Radiographic examination of tank top butt welds must be performed before block erection. Pre-weld NDT checklist updated for Hold No. 2 and 3 blocks.",
    currency: "INR", cost: 42500,
  },
  {
    id: "NCR-2024-0008",
    vessel: "MV Chowgule Dharini (Barge CB-114)", yard: "Chowgule & Co. Shipyard, Goa",
    imoNumber: "9901482",
    location: "Engine Room / Bilge System / Fr.18–22",
    drawingRef: "CCS-PIPE-CB114-BG-018 Rev.2",
    defectType: "Piping", severity: "Major",
    raisedDate: "2024-12-10", targetDate: "2024-12-18",
    status: "In Progress",
    description: "Bilge suction pipe (80NB, SCH40) found with wall thickness 4.1mm at Fr.20 elbow; minimum required per IRS is 5.0mm (corrosion allowance included). Thickness measured by calibrated UT gauge at 8 points around elbow. Risk of failure during ballast voyage in bar-crossing conditions.",
    rootCause: "Material",
    department: "Outfitting",
    raisedBy: "Shri. Rajendra Naik — Marine Inspector",
    responsible: "Shri. Anand Sawant — Manager, Pipe Outfitting",
    authorizedBy: "Smt. Smita Dessai — AGM, Quality Assurance",
    assignedTo: "Shri. Carlos Fernandes — Pipe Fitting Supervisor",
    followedBy: "Shri. Nilesh Gaonkar — QA Engineer, Outfitting",
    reviewedBy: "Surveyor P. Kulkarni — IRS, Goa",
    classSociety: "IRS", classRef: "IRS/CCS/2024/NCR/0017",
    correctiveAction: "Elbow section isolated and removed. Replacement 80NB SCH80 elbow (wall thickness 7.62mm) procured from Mumbai. Hydraulic test at 1.5× working pressure scheduled on fitting completion. IRS close-out survey arranged.",
    currency: "INR", cost: 55000,
  },
]

// ─── Sample Equipment — Indian Vessels ───────────────────────────────────────
export const SAMPLE_EQUIPMENT = [
  {
    id: "EQ-001",
    vessel: "MT Kalpana (Yard No. 445)", yard: "L&T Shipbuilding",
    tag: "ME-01", name: "Main Engine — MAN B&W 6S50ME-C8.2",
    system: "Main Propulsion",
    lastServiceDate: "2024-06-10", nextServiceDate: "2025-06-10",
    notes: "Top overhaul due at 16,000 running hours. Turbocharger cleaning interval 4,000 hrs. Lube oil analysis to be submitted to BV surveyor.",
    failureHistory: [
      { date: "2023-04-02", description: "Fuel injector unit #3 seizure — carbon deposits. Replaced by Wartsila service team.", downtime: 18, cost: 380000, currency: "INR" as const },
      { date: "2023-12-15", description: "Turbocharger surge — nozzle ring fouled. Cleaned and performance test passed.", downtime: 8, cost: 95000, currency: "INR" as const },
    ],
  },
  {
    id: "EQ-002",
    vessel: "OSV Sagar Nidhi II (Yard No. 512)", yard: "HSL Visakhapatnam",
    tag: "AE-02", name: "Aux Generator #2 — Kirloskar KG2-750 / 750 kVA",
    system: "Auxiliary Power",
    lastServiceDate: "2024-09-15", nextServiceDate: "2025-03-15",
    notes: "Recurring bearing wear pattern noted — check lubricating oil quality and TBN. Submit to IRS surveyor at next port call.",
    failureHistory: [
      { date: "2024-01-20", description: "Drive-end bearing failure — overheating. Replacement by OEM (Kirloskar, Pune).", downtime: 14, cost: 185000, currency: "INR" as const },
      { date: "2024-08-05", description: "AVR instability during load test — governor hunting. Recalibrated.", downtime: 4, cost: 22000, currency: "INR" as const },
    ],
  },
  {
    id: "EQ-003",
    vessel: "GRSE Fast Patrol Vessel P-450", yard: "GRSE Kolkata",
    tag: "FP-01", name: "Main Fire Pump — Mather & Platt / 400 m³/hr",
    system: "Fire & Safety",
    lastServiceDate: "2024-10-20", nextServiceDate: "2025-04-20",
    notes: "IRS class survey due April 2025. Pump performance test (flow vs pressure) records to be submitted. Impeller wear limits per maker manual.",
    failureHistory: [
      { date: "2023-11-10", description: "Impeller wear — flow rate reduced to 310 m³/hr (min 360). Impeller replaced.", downtime: 6, cost: 58000, currency: "INR" as const },
    ],
  },
]
